<?php
/**
 * FIXME: Edit Title Content
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// FIXME: Fix documentation
// Load elements


// FIXME: Fix documentation
// Load elements
	require_once( get_template_directory() . '/elements/portfolio-lite.php' );
	require_once( get_template_directory() . '/elements/slider-lite.php' );
	require_once( get_template_directory() . '/elements/boxes.php' );
	require_once( get_template_directory() . '/elements/twitter-bar.php' );

// main blog drag and drop options
function cyberchimps_selected_elements() {
	$options = array(
			'boxes'				 => __( 'Boxes', 'cyberchimps' ),
			"portfolio_lite"	 => __( 'Portfolio Lite', 'cyberchimps' ),	
			"blog_post_page"	 => __( 'Post Page', 'cyberchimps' ),
			"slider_lite"		 => __( 'Slider Lite', 'cyberchimps' ),
			"twitterbar_section" => __( 'Twitter Bar', 'cyberchimps' )
		);
	return $options;
}
add_filter( 'cyberchimps_elements_draganddrop_options', 'cyberchimps_selected_elements' );

function cyberchimps_selected_page_elements() {
	$options = array(
			'boxes'				 => __( 'Boxes', 'cyberchimps' ),
			"portfolio_lite"	 => __( 'Portfolio Lite', 'cyberchimps' ),	
			"page_section"	 => __( 'Page', 'cyberchimps' ),
			"slider_lite"		 => __( 'Slider Lite', 'cyberchimps' ),
			"twitterbar_section" => __( 'Twitter Bar', 'cyberchimps' )
		);
	return $options;
}
add_filter( 'cyberchimps_elements_draganddrop_page_options', 'cyberchimps_selected_page_elements' );