<?php
/**
 * Title: Parallax Element
 *
 * Description: Adds parallax effect to different elements.
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if( !defined( 'ABSPATH' ) ) {
	die( '-1' );
}

// Add parallax library.
add_action( 'wp_enqueue_scripts', 'cyberchimps_parallax_scripts' );
function cyberchimps_parallax_scripts() {

	// Add parallax js library.
	wp_enqueue_script( 'parallax-js', get_template_directory_uri() . '/elements/lib/js/jquery.parallax.js', array( 'jquery' ) );
}

// Set parallax to individual elements by checking toggle.
add_action('wp_footer', 'cyberchimps_parallax_setings');
function cyberchimps_parallax_setings() {
?>
	<script>
		jQuery(document).ready(function() {
			jQuery('.container-full-width').parallax('50%', 0.4);
			jQuery('body').parallax('50%', 0.7);
		});
	</script>
<?php
} ?>
<style type="text/css">
	#boxes_lite_section {
		background: url("<?php echo get_template_directory_uri() . '/elements/lib/images/parallax.jpg' ?>");
		height: 350px;
		padding-top: 100px;
	}
</style>