<?php
/**
 * Title: Testimonial Element
 *
 * Description: Defines custom post type "testimonial".
 *                Defines action to be done when element "testimonial" is active.
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

// Don't load directly
if( !defined( 'ABSPATH' ) ) {
	die( '-1' );
}

if( !class_exists( 'CyberChimpsTestimonial' ) ) {
	class CyberChimpsTestimonial {

		protected static $instance;
		public $options;

		/* Static Singleton Factory Method */
		public static function instance() {
			if( !isset( self::$instance ) ) {
				$className      = __CLASS__;
				self::$instance = new $className;
			}

			return self::$instance;
		}

		/**
		 * Initializes plugin variables and sets up WordPress hooks/actions.
		 *
		 * @return void
		 */
		protected function __construct() {
			add_action( 'testimonial', array( $this, 'render_display' ) );
			$this->options = get_option( 'cyberchimps_options' );
			
		}
		/**
		 * Puts markup for testimonial
		 *
		 * @return void
		 */
		public function render_display() {

			// Get the default image of carousel
			$default = get_template_directory_uri() . apply_filters( 'cyberchimps_testimonial_img', '/cyberchimps/lib/images/testimonial.jpg' );
			$custombackground = cyberchimps_get_option('testimonial_background');

			if( is_page() ) {
				$customcategory = get_post_meta( get_the_ID(), 'testimonial_category', true );
				$custombackground = get_post_meta( get_the_ID(), 'testimonial_background', true );			

				if($custombackground == ""){
?>
					<style type="text/css" media="all">
						#testimonial_section{ 
							background : url("<?php echo $default; ?>") no-repeat scroll 0 0 / cover;
						}	
					</style>
<?php
				}
				else{
?>
					<style type="text/css" media="all">
						#testimonial_section{ 
							background : url("<?php echo $custombackground; ?>") no-repeat scroll 0 0 / cover;
						}	
					</style>
<?php
				}			
			}

			else {
				
				$customcategory_obj     = ( isset( $this->options['testimonial_categories'] ) ) ? get_term( $this->options['testimonial_categories'], 'testimonial_categories' ) : '';
				$customcategory     = ( isset( $this->options['testimonial_categories'] ) ) ? $customcategory_obj->slug : '';
				$custombackground        = $this->options['testimonial_background'];
			}
	
				$args = array(
					'numberposts'         => -1,
					'offset'              => 0,
					'testimonial_categories' => $customcategory,
					'testimonial_background' => $custombackground,
					'orderby'             => 'post_date',
					'order'               => 'ASC',
					'post_type'           => 'testimonial_posts',
					'post_status'         => 'publish',
					'suppress_filters'    => false
				);
		
				$testimonial_posts = get_posts( $args );
			?>
			<div class="container">
				<div id="testimonial_container" class="row">
					<div id="testimonial" class="col-lg-12">
						<div id="gallery-testimonial" class="carousel slide portfolio-section" data-ride="carousel">

							<?php

							if( $testimonial_posts ) { 
								$slide_counter1 = 1; ?>
								 <div role="listbox" class="carousel-inner">

							<?php	foreach( $testimonial_posts as $post ) {

									/* Post-specific variables */
									$image    = get_post_meta( $post->ID, 'testimonial_post_image', true );
									$title    = $post->post_title;
									$testimonial_author    = get_post_meta( $post->ID, 'testimonial_author_name', true );
									$testimonial_text    = get_post_meta( $post->ID, 'testimonial_text', true );
							?>
								
									<div class="testimonial_main_div item <?php echo ( $slide_counter1 == 1 ) ? "active" : ""; ?>">
		                                <div class="testimonial_img col-lg-12 "><img src="<?php echo $image; ?>" alt="<?php echo $title; ?>"/></div>
										<div class="testimonial_author col-lg-12">
											<?php echo $testimonial_author; ?>
										</div>
										<div class="testimonial_text col-lg-12">
											<?php echo $testimonial_text; ?>
										</div>					    
									</div>								
								
							<?php
								$slide_counter1++;
								}// end of foreach ?>
							
								</div> <!-- end of carousel-inner-->
								<a class="carousel-control left slider-left" href="#gallery-testimonial" data-slide="prev">
									<span class="glyphicon glyphicon-chevron-left"></span>
								</a>
								<a class="carousel-control right slider-right" href="#gallery-testimonial" data-slide="next">
									<span class="glyphicon glyphicon-chevron-right"></span>
								</a>
						<?php	} // end of if
							else {
								$image = get_template_directory_uri() . "/cyberchimps/lib/images/portfolio.jpg";
								?>
								<div class="testimonial_main_div item">
		                			<div class="testimonial_img col-lg-12 ">	
										<img src="<?php echo $image; ?>" alt="<?php if(!empty($title)) echo $title; ?>"/>
									</div>
									<div class="testimonial_author col-lg-12">Testimonial Author
									</div>
									<div class="testimonial_text col-lg-12">Sample Text
									</div>
								</div>

							<?php } ?>
						
						</div>	<!-- .es-carousel -->
					</div>	<!-- #carousel -->
				</div><!-- #container -->
			</div><!-- end of .container -->
		<?php
		}
	}
}
CyberChimpsTestimonial::instance();
