/**
 * FIXME: Elements javascript file
 *
 * FIXME: Edit Description Content
 *
 * Please do not edit this file. This file is part of the Cyber Chimps Framework and all modifications
 * should be made in a child theme.
 * FIXME: POINT USERS TO DOWNLOAD OUR STARTER CHILD THEME AND DOCUMENTATION
 *
 * @category Cyber Chimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v2.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

/*	Boxes element make all the same height */

jQuery(document).ready(function($) {
	var tallest_box = 0;
	var height = 0;
	$('#widget-boxes-container .box').each(function(){
		height = $(this).height()
		if( height > tallest_box ){
			tallest_box = height + 20;
		}
	})
		$('#widget-boxes-container .box').css('height', tallest_box + 'px')
	
});